import { ResolvedWorkspaceContext } from '../config/schema.js';

export function renderProjectReadme(context: ResolvedWorkspaceContext): string {
  const { config, commands } = context;

  const adapterDescriptions: Record<string, string> = {
    agents: '- **AGENTS.md**: Standard root instructions for cross-tool AI agents.',
    cursor: '- **Cursor (.cursor/rules/)**: Modular rules for Cursor IDE.',
    claude: '- **Claude Code (CLAUDE.md)**: Guidelines and shell commands for Claude Code CLI.',
    copilot: '- **GitHub Copilot (.github/)**: Workspace prompt instructions for Copilot.',
  };

  const configuredAdaptersList = config.adapters
    .map((id) => adapterDescriptions[id] || `- **${id}**: Configured AI tool adapter.`)
    .join('\n');

  return `# ${config.project.name}

Welcome to **${config.project.name}**. This workspace is initialized with an AI-ready development contract generated by [Foundry](https://github.com/foundry-rs/foundry).

## Application Profile
- **Application Type:** ${config.project.type}
- **Primary Language:** ${config.project.language}
- **Guardrail Strictness:** ${config.strictness}

## Key Development Commands
- **Build:** \`${commands.build}\`
- **Test:** \`${commands.test}\`
- **Dev:** \`${commands.dev}\`
- **Lint:** \`${commands.lint}\`

## Working with AI Coding Assistants
This project maintains consistent, deterministic AI instruction files to ensure that AI assistants (such as Cursor, Claude Code, and Copilot) follow project conventions and guardrails without manual prompt recreation:

${configuredAdaptersList}

For the core architectural guidelines and non-negotiable rules governing this codebase, refer to [\`AGENTS.md\`](./AGENTS.md).
`;
}
